endpoint: http://127.0.0.1:54321/query
transport:
  type: stdio
schema:
  source: local
  path: ./dagger-schema.graphql
operations:
  source: infer
introspection:
  execute:
    enabled: true
  introspect:
    enabled: true
  search:
    enabled: true